export const petsArray = [
    {name: "Mufasa", imageURL: "http://placeimg.com/640/480/animals" },
    {name: "Heihei", imageURL: "http://placeimg.com/640/480/animals" },
    {name: "Abu", imageURL: "http://placeimg.com/640/480/animals" },
    {name: "Burni", imageURL: "http://placeimg.com/640/480/animals" },
    {name: "Sebastian", imageURL: "http://placeimg.com/640/480/animals" },
    {name: "Sven", imageURL: "http://placeimg.com/640/480/animals" },
    {name: "Baloo", imageURL: "http://placeimg.com/640/480/animals" },
    // {name: "Mufasa", imageURL: "https://images.vectorhq.com/images/previews/f49/mufasa-psd-458659.png" },
    // {name: "Heihei", imageURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLbQ6aO-_9vKEriYzS-nH6nTf_UEj6rHjjWg&usqp=CAU" },
    // {name: "Abu", imageURL: "https://www.disneyclips.com/images/images/abu-jugglings.gif" },
    // {name: "Burni", imageURL: "https://wallpaperaccess.com/full/2352954.jpg" },
    // {name: "Sebastian", imageURL: "http://www.cartoonbucket.com/wp-content/uploads/2015/08/Sebastian-Cartoon-Picture.png" },
    // {name: "Sven", imageURL: "https://img.cppng.com/download/2020-06/33014-3-frozen-sven-photo.png" },
    // {name: "Baloo", imageURL: "https://p.kindpng.com/picc/s/0-1554_baloo-the-jungle-book-bear-winnie-the-pooh.png" },
];
