export const petsArray = [
    // {name: "Mufasa", imageURL: "" },
    // {name: "Heihei", imageURL: "" },
    // {name: "Abu", imageURL: "" },
    // {name: "Burni", imageURL: "" },
    // {name: "Sebastian", imageURL: "" },
    // {name: "Sven", imageURL: "" },
    // {name: "Baloo", imageURL: "" },
    {name: "Mufasa", imageURL: "https://images.vectorhq.com/images/previews/f49/mufasa-psd-458659.png" },
    {name: "Heihei", imageURL: "https://www.teahub.io/photos/full/17-173695_heihei-moana-disney-movie-chicken-wallpaper-heihei-in.jpg" },
    {name: "Abu", imageURL: "https://www.kindpng.com/picc/m/36-364780_skiing-clipart-character-disney-aladdin-abu-png-transparent.png" },
    {name: "Burni", imageURL: "https://wallpaperaccess.com/full/2352954.jpg" },
    {name: "Sebastian", imageURL: "http://www.cartoonbucket.com/wp-content/uploads/2015/08/Sebastian-Cartoon-Picture.png" },
    {name: "Sven", imageURL: "https://img.cppng.com/download/2020-06/33014-3-frozen-sven-photo.png" },
    {name: "Baloo", imageURL: "https://p.kindpng.com/picc/s/0-1554_baloo-the-jungle-book-bear-winnie-the-pooh.png" },
];
